version: '3.8'

services:
  users_microservice:
    build:
      context: .
      dockerfile: Dockerfile
    command: "php -S 0.0.0.0:8000 -t public"
    ports:
      - "8000:8000/tcp"
    volumes:
      - .:/app
    depends_on:
      - users_microservice_db

  users_microservice_db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: ultralinks
      MYSQL_PASSWORD: ultralinks
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./storage/dbdata:/var/lib/mysql
    ports:
      - "33061:3306"
